<?php

namespace AppBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
    public function not_rated($user, $code){
        $eval = $this->findBy(['id_produit' => $code, 'id_user' => $user]);
        if($eval == null){
            return true;
        }
        return false;
    }


}
