<?php

namespace AppBundle\Repository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends \Doctrine\ORM\EntityRepository
{
    public function productExists($code){
        $product = $this->findOneBy(array('codeBarre' => $code));
        if($product == null){
            return false;
        }
        return true;
    }

    public function average($code){
        $eval_repo = $this->getEntityManager()->getRepository('AppBundle:Evaluation');
        $evaluations = $eval_repo->findBy(['id_produit' => $code]);
        $total = 0;
        $nb = 0;
        foreach ($evaluations as $evaluation){
            $total += $evaluation->getNote();
            $nb += 1;
        }
        if ($nb != 0){
            $result = $total / $nb;
        }else{
            $result = 'inexistante';
        }

        return $result;
    }

    public function get_8_meilleurs(){
        $eval_repo = $this->getEntityManager()->getRepository('AppBundle:Evaluation');
        $all_products = $eval_repo->createQueryBuilder('fc')
            ->select('AVG(fc.note) as notes, fc.id_produit')
            ->groupBy('fc.id_produit')
            ->orderBy('notes', 'DESC')
            ->setMaxResults(8)
            ->getQuery()
            ->execute();

        return $all_products;
    }
}
